### ISSUE TITLE
Atlas freezes on some addresses

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/mapboard#135]
Examples:
http://atlas.phila.gov/#/4400-10%20MAIN%20ST/property
http://atlas.phila.gov/#/4800%20FORT%20MIFFLIN%20RD/property

**Comment by ajrothwell** [comment]
we found that the freezup is caused by zoning overlay polygons being returned that are too large for the browser to handle (ex. 12 MB).

we are going to change the esri-client query to not return geometry automatically.  it will take any options supported by the esri-leaflet query task.
