### ISSUE TITLE
Error during Turf.js area/perimeter calcuations for parcels

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/mapboard#148]
Example: https://atlas.phila.gov/#/1750%20GERMANTOWN%20AVE/property

Error: `Uncaught Error: Each LinearRing of a Polygon must have 4 or more Positions.`

These are probably multipart polygons that need special handling.

**Comment by ajrothwell** [comment]
I wrote a function to calculate the perimeter
