### ISSUE TITLE
Migrate content from Atlas

### ISSUE THREAD

**Issue by ajrothwell** [CityOfPhiladelphia/mapboard#17]
- [ ] Related Addresses
- [x] Assessments
- [x] Deeds
  - [x] Parcel Details
  - [x] Documents
  - [x] Registry Maps
- [x] Permits
- [x] Zoning
- [x] Water
- [x] Vacancy
- [x] 311

**Comment by rbrtmrtn** [comment]
- [ ] Related Addresses
- [ ] Assessments
- [ ] Deeds
  - [ ] Parcel Details
  - [ ] Documents
  - [ ] Registry Maps
- [ ] Permits
- [ ] Zoning
- [ ] Water
- [ ] Vacancy
- [ ] 311

**Comment by rbrtmrtn** [comment]
Remaining tasks will be migrated to individual issues.
