### ISSUE TITLE
error logging

### ISSUE THREAD

**Issue by ajrothwell** [CityOfPhiladelphia/mapboard#20]

**Comment by rbrtmrtn** [comment]
Sentry:
https://sentry.io/welcome/

**Comment by rbrtmrtn** [comment]
Make sure production CityAtlas and Atlas have the right Sentry tokens.

**Comment by rbrtmrtn** [comment]
Implemented in e06d13a94d607731142e5ed3d19baf1056071e70 and 803bdc7838784be878da37ec31b759890199d1a2
