### ISSUE TITLE
Data Source Inventory

### ISSUE THREAD

**Issue by ajrothwell** [CityOfPhiladelphia/mapboard#31]

**Comment by rbrtmrtn** [comment]
The purpose of this issue was to catalog Atlas data sources and determine if they're production-ready or not. Some of the topics have content which is not regularly updated and/or requires a new ETL process.

**Comment by ajrothwell** [comment]
I have put all large PowerPoint diagrams in a public folder:
\\city.phila.local\shares\GroupsNew\DOT\Groups\Enabling Technology Services\GSG\Projects\Open_Projects\mapboard\PowerpointDiagrams

the one called MapBoard_DataFlowConfigToStateToUI.pptx has this inventory

I have also tried putting all endpoints in geomonitor, but it constantly shows some of them down while they are not, so I did not complete that.
