### ISSUE TITLE
Browser compatibility tests

### ISSUE THREAD

**Issue by ajrothwell** [CityOfPhiladelphia/mapboard#32]

**Comment by rbrtmrtn** [comment]
Look into integrating BrowserStack into production build tests. Credentials are in LastPass.

**Comment by rbrtmrtn** [comment]
Not automating tests for now -- just open Atlas in BrowserStack and make sure it works on IE and Safari.

**Comment by rbrtmrtn** [comment]
See https://github.com/CityOfPhiladelphia/mapboard/issues/126
