### ISSUE TITLE
Parcel Tiles for Imagery need to be rebuilt

### ISSUE THREAD

**Issue by ajrothwell** [CityOfPhiladelphia/mapboard#64]

**Comment by ajrothwell** [comment]
http://tiles.arcgis.com/tiles/fLeGjb7u4uXqeF9q/arcgis/rest/services/ParcleTile/MapServer/

need to start with world, instead of city, cause they are off by ~10 zoom levels.  They don't come on correctly, but they fix themselves when they zoom

**Comment by rbrtmrtn** [comment]
Tim H. published a new service which resolved this.
