### ISSUE TITLE
Cyclomedia widget doesn't work in IE 11

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/mapboard#76]
The console is showing CORS errors saying that "`__ob__` was not found in the Access-Control-List-Header" (or something like that). This seems to be an issue with Vue observing something in the Cyclomedia viewer object. Try taking the viewer out of the Vuex state.

**Comment by Leksat** [comment]
This issue was the first search result when I googled a solution for the same problem.

Error message: `Request header __ob__ was not present in the Access-Control-Allow-Headers list.`

My workaround:
```
    if (requestInfo.headers) {
      // Previously header were set in the init object like this:
      //   headers: new Headers(requestInfo.headers || {}),
      // Then we met "Request header __ob__ was not present in the
      // Access-Control-Allow-Headers list" error in IE.
      // Some debugging showed that ANY object created with object literal
      // notation is observed by Vue and has a hidden __ob__ property. The
      // property never shows up in Chrome/Firefox, and somehow it works fine
      // with most of the code in IE, but it plays a bad joke with the request
      // headers in IE.
      // Further experiments showed that objects created with "new Object()"
      // constructor are not affected, i.e. not observed, so they are safe to
      // use in IE.
      const headers = new Object();
      for (const headerName of Object.keys(requestInfo.headers)) {
        const headerValue = requestInfo.headers[headerName];
        headers[headerName] = headerValue;
      }
      init.headers = new Headers(headers);
    }
```
I know it's not perfect (it's almost 3am:)), but works.

I'm not sure why Vue does that - observes all objects. I expected it to observe only the store and the local component state.

**Comment by rbrtmrtn** [comment]
Wow, thanks @Leksat! I think we worked around it another way but I can't remember how off the top of my head. Will keep this in mind in case it comes back up. Good to know we aren't the only ones who ran into this :)
